### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by Riverhate** [dgomes/ha_prosegur#2]
The integration doesn't logging with my prosegur user and password app, please help

**Comment by dgomes** [comment]
Do you have access to https://smart.prosegur.com/smart-individuo/login.html#!/ ?

**Comment by Riverhate** [comment]
Now the link redirect to: https://alarmas.movistarproseguralarmas.es and yes I have access, any  Idea?

**Comment by Riverhate** [comment]
> Now the link redirect to: https://alarmas.movistarproseguralarmas.es and yes I have access, any Idea?

when I try to add the integration, after write user and password, the integration answer "Invalid authentication" and it is not possible to install it.

**Comment by dgomes** [comment]
You seam to have your alarm connected to a different platform, currently only the smart.prosegur.com is supported...

**Comment by Riverhate** [comment]
> You seam to have your alarm connected to a different platform, currently only the smart.prosegur.com is supported...

Thank you!!

**Comment by Albruaje** [comment]
But smart.prosegur.com is no longer supported by prosegur....

**Comment by dgomes** [comment]
> But smart.prosegur.com is no longer supported by prosegur....

Why do you say that ? Were I live it's the only one available

**Comment by Albruaje** [comment]
> > But smart.prosegur.com is no longer supported by prosegur....
> 
> Why do you say that ? Were I live it's the only one available

Here in Spain it has been replaced by: https://alarmas.movistarproseguralarmas.es

**Comment by dgomes** [comment]
@Albruaje are you skilled running python code ? I could create a test to see if it is any different the API's

Check the supporting library: https://github.com/dgomes/pyprosegur

If we make it work in the supporting library, then I can make it work in HA

**Comment by Albruaje** [comment]
I'm affraid I'm don't know about python code, but I can help you on any test you may need.

**Comment by dgomes** [comment]
But can you run python from the command line ?

**Comment by Albruaje** [comment]
> But can you run python from the command line ?

I'm affraid not

**Comment by Albruaje** [comment]
Thanks! It works with the new version in Spain. Now I will work to detect events and act. Thanks!

**Comment by dgomes** [comment]
All credits go to Magnus Mølsæter who assisted me by testing the new code

**Comment by Riverhate** [comment]
Hi, Thanks dgomes, with the lates version it works in Spain!!!
