### ISSUE TITLE
Configuration and setup outside Spain and Portugal

### ISSUE THREAD

**Issue by efrenmartin** [dgomes/ha_prosegur#5]
Hi. I am a Prosegur user in Argentina and I am trying to set this integration up but I am not able since the integration only shows the forementioned countries. I run the alarm remote app on my family's phones and it works almost perfectly.  I wish to set up some automations in HomeAssistant. 

Any reading/work you can suggest in order to be able to use the integration in my country?

![image](https://user-images.githubusercontent.com/11235332/162791409-6499fca6-4090-4cf3-9a96-d62c3ca60265.png)

**Comment by dgomes** [comment]
This integration is obsolete as current version is officially part of Home Assistant

That being said, there might be the chance to support your country:

- I don't know if Argentina shares the same API as Portugal and Spain. Which website do you use to control your alarm ?

**Comment by efrenmartin** [comment]
We use the phone app so I should do some research to know where it connects to... 
on the other hand we do NOT use the web app but I just logged into it:

![image](https://user-images.githubusercontent.com/11235332/162824695-644d9b0c-7e51-43af-9350-4d2795fd918e.png)

They both share the identities. The app seems to be the same everywhere, since the end user trainig videos do not look localized...

**Comment by efrenmartin** [comment]
![imagen](https://user-images.githubusercontent.com/11235332/163735925-05629611-21e9-4d09-b254-1c2724a39116.png)
 This are the DNS requests that go to my local pihole when loading the app on my phone

**Comment by dgomes** [comment]
Well you logged into the web app successfully, can you actually use it ? If true you can probably test it using "PT"

**Comment by efrenmartin** [comment]
Integration working for my contract! Thanks!

**Comment by dgomes** [comment]
so I can add "AR"  :) ?

**Comment by efrenmartin** [comment]
:-D
Efren
