### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by pccsoares** [dgomes/ha_prosegur#6]
I tried the official version, not sure if it is in sync with this repo, but it's not working for me. 
After selecting PT and adding successfully the integration, it shows no entities, not allowing me to arm or disarm. 
Is this still working? 
Not sure if this can be cause by my Prosegur account having two separate installations.

**Comment by dgomes** [comment]
Hi!

I will need some help from you to get this debugged.

Are you able to install the latest version of this integration as a custom_component? I can guide you through the process, reach out for me on Home Assistant Discord (I go by @dgomes)
